
//silver_chain_scope_start
//mannaged by silver chain
#include "../imports/imports.api_globals.h"
//silver_chain_scope_end
#define  CAMALGAMATOR_FILE_NOT_FOUND 1
#define  CAMALGAMATOR_OK 0
enum{
    PRIVATE_CAMALGAMATOR_NORMAL_STATE,
    PRIVATE_CAMALGAMATOR_WATING_FILENAME_STRING_START,
    PRIVATE_CAMALGAMATOR_COLLECTING_FILENAME,
    PRIVATE_CAMALGAMATOR_INSIDE_INLINE_COMENT,
    PRIVATE_CAMALGAMATOR_INSIDE_MULTILINE_COMENT,
    PRIVATE_CAMALGAMATOR_INSIDE_NORMAL_STRING,
    PRIVATE_CAMALGAMATOR_INSIDE_CHAR
};
#ifndef  CAMALGAMATION_PLOTAGE_FOLDER
#define CAMALGAMATION_PLOTAGE_FOLDER "amalgamation_plotage"
#endif
